### ISSUE TITLE
Testing database

### ISSUE THREAD

**Issue by nokout** [AusDTO/disco_crawl#10]
Look at adding a test config for sequelise to use a sqlite database file with a known state instead of a postgres database. This would allow simple testing of the database layer.

**Comment by nokout** [comment]
Refer: 
http://cmme.org/tdumitrescu/blog/2014/02/node-sql-testing/
http://sethlakowske.com/software/sequelize-unit-testing-using-grunt-and-nodeunit/
https://www.npmjs.com/package/sequelize-fixtures

**Comment by monkeypants** [comment]
Fixtures are cool, but fixture-factories are cooler (because they don't break when you change the model, as much). Ruby's factory_girl is kind of the canonical example, and somebody made a sequelize module for it:

https://github.com/aexmachina/factory-girl-sequelize

I haven't used either (ruby) but because it's useful, of course there is a python version (factory_boy):

https://factoryboy.readthedocs.org/

I'm not aware of a sequelize builder for it.

This is probably only relevant if you expected keep changing your webDocument class over time. sequelize-fixtures looks cool for the timebeing.

Note that with discoveryLayer, the following command will generate a json fixture files from existing crawler database content:

    django-admin dumpdata --format=json --indent=4 --output=fixtures/dumpedones.json crawler

see here for documentation:

https://docs.djangoproject.com/en/1.8/ref/django-admin/#dumpdata-app-label-app-label-app-label-model
